name = "UUID4"
uuid = "379725f3-1ad5-416d-b88a-50ced391fe04"
authors = ["Heptazhou <zhou at 0h7z dot com>"]
version = "1.10.0"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[extras]
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["OrderedCollections", "Test"]
